# Generated by Django 5.2.4 on 2025-07-27 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='applicationdatastoredependency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datastore_dependencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationdatastoredependency',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='applicationdatastoredependency',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_datastore_dependencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationlanguagedependency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_language_dependencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationlanguagedependency',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='applicationlanguagedependency',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_language_dependencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationlifecycleevent',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='cloudplatform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cloud_platforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cloudplatform',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='cloudplatform',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cloud_platforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cloudplugin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cloud_plugins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cloudplugin',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='cloudplugin',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cloud_plugins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datastore',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datastores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datastore',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='datastore',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_datastores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datastoreinstance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datastore_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datastoreinstance',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='datastoreinstance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_datastore_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languageinstallation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_language_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languageinstallation',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='languageinstallation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_language_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serverenvironment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serverenvironment',
            name='system_manager_notes',
            field=models.TextField(blank=True, help_text='Only visible to Systems Managers and Application Admins'),
        ),
        migrations.AddField(
            model_name='serverenvironment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('application_admin', 'Application Admin'), ('systems_manager', 'Systems Manager'), ('technician', 'Technician'), ('business_manager', 'Business Manager'), ('business_user', 'Business User')], default='business_user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='RecordPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('permission_type', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read/Write'), ('full', 'Full Access')], default='read', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
