# Generated by Django 5.2.4 on 2025-07-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_application_system_manager_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_documentation_access',
            field=models.BooleanField(default=False, help_text='Access to system documentation at /docs'),
        ),
    ]
