# Generated by Django 5.2.4 on 2025-07-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_userprofile_has_documentation_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdatastoredependency',
            options={'ordering': ['application', '-is_primary', 'datastore_instance'], 'verbose_name': 'Application Data Store Dependency', 'verbose_name_plural': 'Application Data Store Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='applicationlanguagedependency',
            options={'ordering': ['application', '-is_primary', 'language_installation'], 'verbose_name': 'Application Language Dependency', 'verbose_name_plural': 'Application Language Dependencies'},
        ),
    ]
