version: '3.8'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: app_tracker
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  app:
    image: app-tracker-app:latest
    environment:
      - DATABASE_URL=mysql://appuser:apppassword@db:3306/app_tracker
      - DEBUG=False
      - DJANGO_SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  nginx:
    image: app-tracker-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  mysql_data:

networks:
  app-network:
    driver: overlay
    attachable: true
