services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: app_tracker
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: app-tracker-app:latest
    environment:
      - DATABASE_URL=mysql://appuser:apppassword@db:3306/app_tracker
      - DEBUG=False
      - DJANGO_SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: app-tracker-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
